[package]
name = "tor-protover"
version = "0.29.0"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2021"
rust-version = "1.77"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Implementation for Tor's subprotocol versioning"
keywords = ["tor", "arti"]
categories = ["network-programming"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[dependencies]
caret = { path = "../caret", version = "0.5.0" }
paste = "1"
serde_with = { version = "3.0.0", optional = true }
thiserror = "2"

[features]
default = []
full = ["caret/full", "serde"]
serde = ["serde_with"]

[package.metadata.docs.rs]
all-features = true
